### ISSUE TITLE
error index type in event

### ISSUE THREAD

**Issue by zhankun** [dakrone/elasticsearch-in-action#18]
when we create data by populate.sh,string type is not 'string', it created to 'type':'text'.In code case 7-10,we need "aggregation" on field "attendees",at this moment will cause error :
Fielddata is disabled on text fields by default. Set fielddata=true on [attendees] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
my es version is :5.6.8

**Comment by radu-gheorghe** [comment]
Thanks for reporting, @zhankun! In this case, typically you'll also have a keyword field for aggregations. Let's call it `verbatim`:

```
"attendees": {
  "type": "text",
  "fields": {
    "verbatim": {
      "type": "keyword
}}}
```

And then you'd aggregate on `attendees.verbatim` instead of `attendees`. The point is, `text` is analyzed string, which works for full-text search, and `keyword` is the not_analyzed string, which works for exact matche, sorting and aggregations. Neither use field data by default, but keywords us doc_values, which are on-disk, typically more efficient implementation of field data. There is an explanation in the book about the difference between the two.

Does this help? If yes, I can go ahead and update the mapping.json here to add a keyword for `attendees`.

**Comment by zhankun** [comment]
Thanks for your help,I'll add and then test it!

**Comment by radu-gheorghe** [comment]
You're welcome!

**Comment by zhankun** [comment]
After upadte mapping.json with your suggest,It working!

**Comment by radu-gheorghe** [comment]
Awesome! I added a commit to the 6.x branch with the changes above.
